# -*- coding: utf-8 -*-
"""Project Phyton Pacmann.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/12p8jJ6TsSNPL9XlKyBLoDnfPJlQR_iAn
"""

from tabulate import tabulate

print("---- WELCOME TO SELF-SERVICE CASHIER ----")
trnsct_123 = input("Input Your Transaction ID: ")
print ("Transaction ID :", trnsct_123) 

print("\n---- Shopping Item ----")
choice = 'y'
data=[]
grand_total = 0

while choice == 'y':
  add_item = input("Input your item: ").split(",")
  grand_total = grand_total + (int(add_item[1])*int(add_item[2])) 
  choice = input("add Item? (y / n): ")
  data.append(add_item)
  if choice.casefold() == "n":
    break
 
print("\n=======  CART SUMMARY  =======")
print(tabulate(data, headers=["Item Name","QTY", "Price", "Grand Total"], tablefmt="orgtb"))
print("Grand Total: ", grand_total)

#Next To Do
print("\n------------  LANGKAH SELANJUTNYA  ------------")
next_todo = input("Apa Yang Ingin Anda Lakukan Selanjutnya?\n   - Ketik 'update' untuk ubah daftar belanja  \n   - ketik 'hapus' untuk menghapus belanja  \n   - ketik 'selesai' untuk melihat ringkasan belanja Anda  \n   - ketik 'reset' untuk melihat ringkasan belanja Anda  \n")


if next_todo == "update":
 
  user_list_input = int(input("List Nomor Berapa Yang Akan di-update?"))
  user_item_input = int(input("Bagian Mana yang akan di-update?\n   - Item Name ketik '1' \n   - Qty ketik '2' \n   - Price ketik '3' \n"))
  user_update = input("Masukan Data Baru: ")
  data[user_list_input-1][user_item_input-1] = user_update

  if user_item_input == 2:
    total_update = grand_total + (int(user_update)*int(add_item[2])) 
  elif user_item_input == 3:
    total_update = grand_total + (int(user_update)*int(add_item[1]))
  elif user_item_input == 1:
    total_update = grand_total + (int(add_item[1])*int(add_item[2]))
  
  input(data[user_list_input-1])

  print("\n\n=======  CART SUMMARY UPDATED  =======")
  print(tabulate(data, headers=["Item Name","QTY", "Price", "Grand Tbotal"], tablefmt="orgtb"))
  print("Grand Total: ", total_update)

  confirm = input("Apakah Pesanan Sudah Selesai? (y/n)")
  if confirm == "y":
    print("\n\n------ Berikut Yang Harus dibayar ------")
    if 200000 < total_update < 300000:
      total_bayar = (total_update - (0.05 * total_update))
    elif 300000 < total_update < 500000:
      total_bayar = (total_update - (0.08 * total_update))
    elif total_update > 500000:
      total_bayar = (total_update - (0.1 * total_update)) 
    print("\n=======  CART SUMMARY FINAL  =======")
    print(tabulate(data, headers=["Item Name","QTY", "Price", "Grand Total"], tablefmt="orgtb"))
    print("Grand Total: ", total_update)

    #Print Label Pemberitahuan Diskon
    if 200000 < total_update < 300000 :
      print("Anda Mendapat Diskon 5%, total bayar menjadi:", total_bayar)
    elif 300000 < total_update < 500000:
      print("Anda Mendapat Diskon 8%, total bayar menjadi:", total_bayar)
    elif total_update > 500000:
      print("Anda Mendapat Diskon 10%, total bayar menjadi:", total_bayar) 
  if confirm == "n":
     next_todo = input("Apa Yang Ingin Anda Lakukan Selanjutnya?\n   - Ketik 'update' untuk ubah daftar belanja  \n   - ketik 'hapus' untuk menghapus belanja  \n   - ketik 'selesai' untuk melihat ringkasan belanja Anda  \n   - ketik 'reset' untuk melihat ringkasan belanja Anda  \n")


if next_todo == "hapus":

  user_list_input = int(input("List Nomor Berapa Yang Akan dihapus?"))
  input(data[user_list_input-1])
  hapus = input("Apakah Anda Yakin (y/n)?")
  if hapus == "y":
    del data[user_list_input-1]
    print("\n\n=======  CART SUMMARY UPDATED  =======")
    print(tabulate(data, headers=["Nama Barang","QTY", "Harga", "Grand Total"], tablefmt="orgtb"))
    #print("Total Belanja: ", total_update)
   
  confirm = input("Apakah Pesanan Sudah Selesai? (y/n)")
  if confirm == "y":
   print("\n\n------ Berikut Yang Harus dibayar ------")
   if 200000 < total_update < 300000:
    total_bayar = (total_update - (0.05 * total_update))
   elif 300000 < total_update < 500000:
    total_bayar = (total_update - (0.08 * total_update))
   elif total_update > 500000:
    total_bayar = (total_update - (0.1 * total_update)) 
   print("\n=======  CART SUMMARY FINAL  =======")
   print(tabulate(data, headers=["Item Name","QTY", "Price", "Grand Total"], tablefmt="orgtb"))
   print("Grand Total: ", total_update)

   #Print Label Pemberitahuan Diskon
   if 200000 < total_update < 300000 :
    print("Anda Mendapat Diskon 5%, total bayar menjadi:", total_bayar)
   elif 300000 < total_update < 500000:
    print("Anda Mendapat Diskon 8%, total bayar menjadi:", total_bayar)
   elif total_update > 500000:
    print("Anda Mendapat Diskon 10%, total bayar menjadi:", total_bayar) 
     
   if confirm == "n":
    next_todo = input("Apa Yang Ingin Anda Lakukan Selanjutnya?\n   - Ketik 'update' untuk ubah daftar belanja  \n   - ketik 'hapus' untuk menghapus belanja  \n   - ketik 'selesai' untuk melihat ringkasan belanja Anda  \n - ketik 'reset' untuk melihat ringkasan belanja Anda  \n ")
  elif hapus == "n":
    next_todo = input("Apa Yang Ingin Anda Lakukan Selanjutnya?\n   - Ketik 'update' untuk ubah daftar belanja  \n   - ketik 'hapus' untuk menghapus belanja  \n   - ketik 'selesai' untuk melihat ringkasan belanja Anda  \n - ketik 'reset' untuk melihat ringkasan belanja Anda  \n ")

if next_todo == "reset":
  del data[:]
  print("Seluruh Transaksi berhasil dihapus!")

if next_todo == "selesai":
  
  print("\n\n------ Berikut Yang Harus dibayar ------")
  if 200000 < grand_total < 300000:
   total_bayar = (grand_total - (0.05 * grand_total))
  elif 300000 < grand_total < 500000:
   total_bayar = (grand_total - (0.08 * grand_total))
  elif grand_total > 500000:
   total_bayar = (grand_total - (0.1 * grand_total)) 
  print("\n=======  CART SUMMARY FINAL  =======")
  print(tabulate(data, headers=["Item Name","QTY", "Price", "Grand Total"], tablefmt="orgtb"))
  print("Grand Total: ", grand_total)

  #Print Label Pemberitahuan Diskon
  if 200000 < grand_total < 300000 :
   print("Anda Mendapat Diskon 5%, total bayar menjadi:", total_bayar)
  elif 300000 < grand_total < 500000:
   print("Anda Mendapat Diskon 8%, total bayar menjadi:", total_bayar)
  elif grand_total > 500000:
   print("Anda Mendapat Diskon 10%, total bayar menjadi:", total_bayar)